// src/screens/Elements/en.js
const en = {
    vendorManager: "Vendor Manager",
    home: "Home",
    clients: "Clients",
    users: "Users",
    contact: "Contact",
    email: "Email",
    chooseVendor: "Choose a vendor",
    selectVendor: "--Select a vendor--",
    edit: "Edit",
    generateReport: "Generate Report",
    newVendor: "New Vendor",
    editVendor: "Edit Vendor",
    addNewVendor: "Add New Vendor",
    vendorName: "Vendor Name",
    vendorAddress: "Vendor Address",
    parametersFor: "Parameters for",
    waterPH: "Water pH",
    calciumLevel: "Calcium Level",
    copperLevel: "Copper Level",
    remove: "Remove",
    newParameterName: "New Parameter Name",
    addParameter: "Add Parameter",
    quickAddParameter: "Quick Add Parameter",
    selectParameter: "--Select a parameter--",
    save: "Save",
    cancel: "Cancel",
    noValueSet: "No value set",
    generatingReport: "Generating a new report for the selected vendor",
    login: "Login",
    username: "Username",
    password: "Password",
    enterValidCredentials: "Please enter valid credentials",
    usernamePlaceholder: "Enter your username",
    passwordPlaceholder: "Enter your password",
    about: "About",
    services: "Services",
    organomex: "Organomex",
    layouts: "Client Manager (Reports)",
    selectOptions: "Select Options",
    selectVendor: "Select Vendor",
    selectVendorPlaceholder: "--Select a vendor--",
    chemist: "Chemist",
    rohm: "Rohm",
    vendor3: "Vendor 3",
    selectChartType: "Select Chart Type",
    pieChart: "Pie Chart",
    barChart: "Bar Chart",
    generate: "Generate",
    usersManagement: "Users Manager",
    userType: "User Type",
    id: "ID",
    details: "Details",
    permissions: "Permissions",
    Client: "Client",
    Worker: "Worker",
    MasterData: "Master Data Analyst",
    editPermissions: "Edit Permissions",
    selectOptions: "Select Options",
    selectVendor: "Select Vendor",
    selectVendorPlaceholder: "--Select a vendor--",
    selectMonth: "Select Month",
    selectMonthPlaceholder: "--Select a month--",
    selectYear: "Select Year",
    selectYearPlaceholder: "--Select a year--",
    ourServices: "Our Services",
    consulting: "Consulting",
    consultingDescription: "We provide expert consulting services to help you achieve your business goals.",
    dataAnalysis: "Data Analysis",
    dataAnalysisDescription: "In-depth data analysis services to gain insights and drive decision making.",
    development: "Development",
    developmentDescription: "Custom software development tailored to your needs.",
    support: "Support",
    supportDescription: "Ongoing support to ensure the success of your projects.",
    register: "Register",
    registerButton: "Register",
    forgotPassword: "Forgot Password?",
    forgotPasswordDescription: "Enter your email to receive password reset instructions.",
    emailLabel: "Email",
    emailPlaceholder: "Enter your email",
    sendInstructions: "Send Instructions",
    resetEmailSent: "Password reset instructions have been sent to your email.",
    enterValidEmail: "Please enter a valid email address.",
    backToLogin: "Back to Login",
    addUser: "Add User",
    remove: "Remove",
    selectUserType: "Select User Type",
    userId: "User ID",
    userName: "Name",
    client: "Client",
    worker: "Worker",
    masterData: "Master Data",
    companyName: "Company Name",
    position: "Position",
    permissionType: "Permission Type",
    actions: "Actions",
    reportManager: "Report Manager",
    userManager: "User Manager",
    generatingReport: "Generating report...",
    clientManager: "Client Manager (Reports)",
    chooseClient: "Choose a client",
    selectClient: "--Select a client--",
    waterPH: "Water pH",
    calciumLevel: "Calcium Level",
    copperLevel: "Copper Level",
    conductivity: "Conductivity",
    tdsLevel: "TDS Level",
    tssLevel: "TSS Level",
    manageParameters: "Manage Parameters",
    parameterManager: "Parameter Manager",
    addRemoveParameters: "Add or Remove Parameters",
    parameterName: "Parameter Name",
    parameterUnit: "Parameter Unit",
    addParameter: "Add Parameter",
    parametersFor: "Parameters for",
    addCondition: "Add Condition",
    conditions: "Conditions",
    triggerParameter: "Trigger Parameter",
    addParameters: "Add Parameters",
    parametersToAdd: "Parameters to Add",
    reportDate: "Report Date",
    reportSize: "Report Size",
    reportLink: "Link",
    viewReport: "View Report",
    recentReports: "Recent Reports",
    clientName: "Client Name",
    choosePlant: "Choose a plant",
    selectPlant: "--Select a plant--",
    chooseSystem: "Choose a system",
    selectSystem: "--Select a system--"
  };
  
  export default en;
  