// src/language/es.js
const es = {
    vendorManager: "Gestor de Proveedores",
    home: "Inicio",
    clients: "Clientes",
    users: "Usuarios",
    email: "correo",
    contact: "Contacto",
    chooseVendor: "Elige un proveedor",
    selectVendor: "--Selecciona un proveedor--",
    edit: "Editar",
    generateReport: "Generar Informe",
    newVendor: "Nuevo Proveedor",
    editVendor: "Editar Proveedor",
    addNewVendor: "Añadir Nuevo Proveedor",
    vendorName: "Nombre del Proveedor",
    vendorAddress: "Dirección del Proveedor",
    parametersFor: "Parámetros para",
    waterPH: "pH del Agua",
    calciumLevel: "Nivel de Calcio",
    copperLevel: "Nivel de Cobre",
    remove: "Eliminar",
    newParameterName: "Nuevo Nombre de Parámetro",
    selectParameter: "--Selecciona un parámetro--",
    save: "Guardar",
    cancel: "Cancelar",
    noValueSet: "Sin valor asignado",
    generatingReport: "Generando un nuevo informe para el proveedor seleccionado",
    login: "Iniciar sesión",
    username: "Nombre de usuario",
    password: "Contraseña",
    enterValidCredentials: "Por favor, introduce credenciales válidas",
    usernamePlaceholder: "Introduce tu nombre de usuario",
    passwordPlaceholder: "Introduce tu contraseña",
    about: "Acerca de",
    services: "Servicios",
    organomex: "Organomex",
    generateReport: "Generar Reporte",
    layouts: "Administrador de clientes",
    selectOptions: "Seleccionar Opciones",
    selectVendor: "Seleccionar Proveedor",
    selectVendorPlaceholder: "--Seleccione un proveedor--",
    chemist: "Químico",
    rohm: "Rohm",
    vendor3: "Proveedor 3",
    selectChartType: "Seleccionar Tipo de Gráfico",
    pieChart: "Gráfico de Pastel",
    barChart: "Gráfico de Barras",
    generate: "Generar",
    usersManagement: "Gestión de Usuarios",
    userType: "Tipo de Usuario",
    id: "ID",
    details: "Detalles",
    permissions: "Permisos",
    Client: "Cliente",
    Worker: "Trabajador",
    MasterData: "Analista de Datos",
    editPermissions: "Editar Permisos",
    selectOptions: "Seleccionar Opciones",
    selectVendor: "Seleccionar Proveedor",
    selectVendorPlaceholder: "--Selecciona un proveedor--",
    selectMonth: "Seleccionar Mes",
    selectMonthPlaceholder: "--Selecciona un mes--",
    selectYear: "Seleccionar Año",
    selectYearPlaceholder: "--Selecciona un año--",
    ourServices: "Nuestros Servicios",
    consulting: "Consultoría",
    consultingDescription: "Ofrecemos servicios de consultoría para ayudar a alcanzar sus objetivos de negocio.",
    dataAnalysis: "Análisis de Datos",
    dataAnalysisDescription: "Servicios de análisis de datos para obtener insights y guiar la toma de decisiones.",
    development: "Desarrollo",
    developmentDescription: "Desarrollo de software personalizado a sus necesidades.",
    support: "Soporte",
    supportDescription: "Soporte continuo para asegurar el éxito de sus proyectos.",
    forgotPassword: "¿Olvidó su contraseña?",
    register: "Registrarse",
    registerButton: "Registrarse",
    forgotPasswordDescription: "Ingrese su correo electrónico para recibir instrucciones de restablecimiento de contraseña.",
    emailLabel: "Correo Electrónico",
    emailPlaceholder: "Ingrese su correo electrónico",
    sendInstructions: "Enviar Instrucciones",
    resetEmailSent: "Las instrucciones para restablecer la contraseña han sido enviadas a su correo electrónico.",
    enterValidEmail: "Por favor, ingrese un correo electrónico válido.",
    backToLogin: "Volver a Iniciar Sesión",
    addUser: "Agregar Usuario",
    remove: "Eliminar",
    selectUserType: "Seleccionar Tipo de Usuario",
    userId: "ID de Usuario",
    userName: "Nombre",
    client: "Cliente",
    worker: "Trabajador",
    masterData: "Datos Maestros",
    companyName: "Nombre de la Empresa",
    position: "Posición",
    permissionType: "Tipo de Permiso",
    actions: "Acciones",
    reportManager: "Gestión de Reportes",
    userManager: "Gestión de Usuarios",
    clientManager: "Gestión de Clientes (Reportes)",
    chooseClient: "Elige un cliente",
    selectClient: "--Selecciona un cliente--",
    waterPH: "pH del Agua",
    calciumLevel: "Nivel de Calcio",
    copperLevel: "Nivel de Cobre",
    conductivity: "Conductividad",
    tdsLevel: "Nivel de TDS",
    tssLevel: "Nivel de TSS",
    manageParameters: "Gestionar Parámetros",
    parameterManager: "Administrador de Parámetros",
    addRemoveParameters: "Agregar o Eliminar Parámetros",
    parameterName: "Nombre del Parámetro",
    parameterUnit: "Unidad del Parámetro",
    addParameter: "Agregar Parámetro",
    parametersFor: "Parámetros para",
    addCondition: "Agregar Condición",
    conditions: "Condiciones",
    triggerParameter: "Parámetro Disparador",
    addParameters: "Agregar Parámetros",
    parametersToAdd: "Parámetros a Agregar",
    recentReports: "Reportes Recientes",
    clientName: "Nombre del Cliente",
    reportDate: "Fecha del Reporte",
    reportSize: "Tamaño del Reporte",
    reportLink: "Enlace",
    viewReport: "Ver Reporte",
  };
  
  export default es;
  